#!/usr/bin/ruby

class SSHConfig
  require 'json'
  require 'erb'

  TEMPLATE = "
<% @hosts.each do |host| %>
Host <%= host[:name] %>
      Hostname <%= host[:private_ip] %>
      User <%= host[:user] %>
<% end %>
  "

  def self.create_file
    user = 'dherman'
    @hosts = SSHConfig.ssh_config(user)
    config = ERB.new(TEMPLATE).result(binding)
    File.open(ENV['HOME'] + '/.ssh/config', 'w') { |file| file.write(config) }
  end

  def self.ssh_config(user)
    hosts = []
    json = JSON.parse(`aws ec2 describe-instances --output json`)['Reservations']
    json.each do |inst|
      host = {}
      instance = inst['Instances'][0]
      host[:private_ip] = instance['PrivateIpAddress']
      host[:name] = SSHConfig.get_tag(instance['Tags'], 'opsworks:instance')
      host[:user] = user
      hosts << host unless host[:name].nil? || host[:private_ip].nil?
    end
    hosts
  end

  def self.get_tag(tags, tag_key)
    return nil unless tags
    tags.each do |tag|
      return tag['Value'] if tag['Key'] == tag_key
    end
    nil
  end
end

SSHConfig::create_file
