#!bin/bash
# Aliases

alias ll='ls -lh'
alias be='bundle exec'
alias vi='vim'
alias ~='cd ~'
alias genssh='~/.ssh/gen_ssh_config'

# Add tab completion for ssh <servername> for Macs (Linux does this by default)
if [[ "$OSTYPE" == "darwin"* ]]; then
  complete -o default -o nospace -W "$(grep "^Host" $HOME/.ssh/config | grep -v "[?*]" | cut -d" " -f2)" scp sftp ssh
fi

# Links to common directories
alias c='cd ~/gdr/projects/'
alias mpl='cd ~/gdr/projects/mpl'
alias mplimport='cd ~/gdr/projects/mpl_import'
alias mplscripts='cd ~/gdr/projects/mpl_scripts'
alias sub='cd ~/gdr/projects/subscriber_portal'
alias doc='cd ~/gdr/projects/doc_control_client'
alias dots='cd ~/dotfiles'
alias cook='cd ~/gdr/projects/cookbook-opsworks' 
# alias dl='cd ~/gdr/projects/'

# Easy editing of aliases file
alias ea='vim ~/.bash/bash_aliases'
alias sa='source ~/.bash/bash_aliases'

# Easy editing of bash_profile
alias eb='vim ~/.bash_profile'
alias sb='source ~/.bash_profile'

# Git shortcuts
alias gc='git commit'
alias gcn='git commit --no-verify'
alias gpull='git pull'
alias gpush='git push'
alias gpushn='git push --no-verify'
alias gco='git checkout'
alias gs='git status'
alias ga='git add .'

# Rails shortcuts
alias lastmigration='vim `last_rails_migration`'

function last_rails_migration {
  find ./db/migrate -type f | xargs ls -tr | tail -n 1
}

# Update dotfiles if there are any changes
alias dotu='for file in $(diff -qr ~/dotfiles ~/ | grep differ | cut -d " " -f 4); do fp "$file"; echo "$file"; done'

function fp {
  cp "$1" ~/dotfiles/"${1#*/*/*/}"
}
