#!bin/bash
# Aliases

alias ll='ls -lh'
alias be='bundle exec'
alias vi='vim'
alias ~='cd ~'
alias genssh='~/.ssh/gen_ssh_config'
alias tmux="TERM=screen-256color-bce tmux"
alias hang="hangups -c ~/hangups/hangups.conf"
alias macnetstat="sudo lsof -PiTCP -sTCP:LISTEN"
alias retmux="tmux attach -d -t 0" # Re-attach to tmux session 0
alias uuid="uuidgen | tr '[:upper:]' '[:lower:]'"
# alias uuid="uuidgen | tr -d - | tr -d '\n' | tr '[:upper:]' '[:lower:]'  | pbcopy && pbpaste && echo"
# killprg() { ps auxww | grep -i $@ | grep -v grep | awk '{ print $2 }' | xargs kill; }

# Links to common directories
alias c='cd ~/projects/'
alias scratch='cd ~/scratch/'
alias dots='cd ~/dotfiles'

# Easy editing of aliases file
alias ea='vim ~/.bash/bash_aliases'
alias sa='source ~/.bash/bash_aliases;echo "Aliases updated"'

# Easy editing of bash_profile
#alias eb='vim ~/.bash_profile'
alias ez='vim ~/.zshrc'
alias sb='source ~/.bash_profile; echo "Bash profile sourced"'
alias sz='source ~/.zshrc; echo "ZSH profile sourced"'

# Easy editing of tmux.conf file
alias et='vim ~/.tmux.conf'

# Git shortcuts
alias gc='git commit'
alias gcu='git reset --soft HEAD~1' # git commit undo
alias gcn='git commit --no-verify'
alias gpull='git pull'
alias gpush='git push'
alias gpushn='git push --no-verify'
alias gco='git checkout'
alias gs='git status'
alias gb='git branch'
alias ga='git add .'
alias gd='git diff'
alias gcd='git log -p -1'
alias gm='git merge'
alias gpushstaging='gco staging;gm master;gpushn;gco master'
alias gpushprod='gco production;gm staging;gpushn;gco master'
alias gpushall='gco staging;gm master;gpushn;gco production;gm staging;gpushn;gco master'
alias gpushb='git push --set-upstream origin'

# Serverless shortcuts
alias slsdf='serverless deploy function --function'
alias slspdf='serverless deploy --stage prod function --function '
alias slsp2df='serverless deploy --stage prod2 function --function '
alias slstdf='serverless deploy --stage test function --function '
alias slssdf='serverless deploy --stage staging function --function '
alias slsddf='serverless deploy --stage demo function --function '
alias slsdft='serverless deploy -t function --function'
alias slsd='serverless deploy --stage dev'
alias slspd='serverless deploy --stage prod'
alias slsp2d='serverless deploy --stage prod2'
alias slssd='serverless deploy --stage staging'
alias slstd='serverless deploy --stage test'
alias slsdd='serverless deploy --stage demo'
alias slsil='AWS_XRAY_CONTEXT_MISSING=LOG_ERROR serverless invoke local --function'
alias slsdebug='export SLS_DEBUG=*'
alias slsnodebug='unset SLS_DEBUG'
alias slsremove='serverless remove --region us-east-1'
alias slsremoves='serverless remove --stage staging --region us-east-1'
alias slsremovep='serverless remove --stage prod --region us-east-1'

# AWS shortcuts
alias awslog='awslogs get $1 ALL -s1h --watch | sed -e 's|$1||''

# Docker shortcuts
alias d='docker'
alias di='docker images'
alias dc='docker ps -a'
alias dfile='vi Dockerfile'
alias dbuild='docker build'
alias drm='docker rm'
alias drun='docker run --rm -it '
alias dstopall='docker kill $(docker ps -q)'
# alias dps="docker ps | awk 'BEGIN{FIELDWIDTHS = \"20 33 23 20 20 60 40 50\"}{print \$1,\$2,\$5,\$7,\$8}'"
alias dps='docker ps --format "table {{.ID}}\t{{.Status}}\t{{.Names}}\t{{.Ports}}" -a'
dexec() { docker exec -i -t $@ /bin/bash ;}
dlog()  { docker logs -f $@ ;}
# dstop() { docker stop $(dps | grep $@ | awk '{print $1}'); }
# dkill() { docker stop $(dps | grep $@ | awk '{print $1}') && docker rm $(dps | grep $@ | awk '{print $1}'); }

# Kubernetes shortcuts
alias k8='kubectl'
alias k8mini='kubectl config use-context minikube'
alias k8switch='kubectl config use-context'
alias k8s='kubectl config get-contexts'

# Node shortcuts
alias lint='npm run lint'
alias nconsole='npm run console'
alias build='npm run build'

# Rails shortcuts
alias rake='be rake'
alias rails='be rails'
alias rspec='be rspec'
alias console='be console'
alias lastmigration='vim `last_rails_migration`'
alias rdbm='be rake db:migrate;RAILS_ENV=test be rake db:migrate'
alias rbenv-update='cd ~/.rbenv;gpull;cd plugins/ruby-build;gpull'

# Go shortcuts
gobuild() { GOOS=linux GO111MODULE=off go build $@.go; }
goget() { go get -d ./...; }
godeploy() {
  rm $@.zip ||
  rm $@ ||
  GOOS=linux GO111MODULE=off go build $@.go &&
  zip -r $@ . &&
  aws lambda update-function-code --function-name $@ --zip-file fileb://$@.zip;
}
gopushaws() { aws lambda update-function-code --function-name $@ --zip-file fileb://$@.zip; }
gozip() { zip -r $@ .;}


# Dot files management
# Check(no changes) to dotfiles if see if there are any changes
alias dotc='for file in $(diff -qr ~/dotfiles ~/ | grep differ | cut -d " " -f 4); do echo "$file"; done'
# Update dotfiles from system to git repo if there are any changes
alias dotu='for file in $(diff -qr ~/dotfiles ~/ | grep differ | cut -d " " -f 4); do fp "$file"; echo "$file"; done'
# Checke(no changes) to Send updated dotfiles to system
alias dotpc='for file in $(diff -qr ~/ ~/dotfiles | grep differ | cut -d " " -f 4); do echo "$file"; done'
# Update dotfiles from git repo to system
alias dotp='for file in $(diff -qr ~/ ~/dotfiles | grep differ | cut -d " " -f 4); do fpp "$file"; echo "$file"; done'

# SSH/SFTP/SCP tabout from SSH config
# complete -o default -o nospace -W "$(grep "^Host" $HOME/.ssh/config | grep -v "[?*]" | cut -d" " -f2)" scp sftp ssh

# Remote tailf command, specify servername to ssh to, and path starting from /var/log to/log/file
# example: remote_tail test-server1 squid/access.log
function remote_tail {
  ssh -t $1 "sudo tailf \"/var/log/$2\""
}

function remote_tail_mpl {
  ssh -t $1 "sudo tailf \"/srv/www/mpl/shared/log/production.log\""
}

function patch_svr {
  ssh -t $1 "sudo yum update -y --skip-broken"
}

function svr_uptime {
  ssh -t $1 "uptime"
}

function fix_clam {
  ssh -t $1 "sudo chown clamav:clamav /var/lib/clamav -R && sudo freshclam"
}

function last_rails_migration {
  find ./db/migrate -type f | xargs ls -tr | tail -n 1
}

function fp {
  cp "$1" ~/dotfiles/"${1#*/*/*/}"
}

function fpp {
  cp -r "$1" ~/"${1#*/*/*/*/}"
}

function top30history {
  echo "function broken"
  # history|awk '{print $2}'|sort|uniq -c|sort -rn|head -30|awk '!max{max=$1;}{r="";i=s=100*$1/max;while(i-->0)r=r"#";printf "%50s %5d %s %s",$2,$1,r,"\n";}'
}

function match_csv_col1 {
  echo "function broken"
  # awk -F',' 'NR==FNR{c[$1]++;next};c[$1] > 0' $1 $2
}

