#!bin/bash
# Aliases

alias ll='ls -lh'
alias be='bundle exec'
alias vi='vim'
alias ~='cd ~'
alias genssh='~/.ssh/gen_ssh_config'
alias tmux="TERM=screen-256color-bce tmux"

# Links to common directories
alias c='cd ~/gdr/projects/'
alias scratch='cd ~/scratch/'
alias mpl='cd ~/gdr/projects/mpl'
alias mplimport='cd ~/gdr/projects/mpl_import'
alias mplstub='cd ~/gdr/projects/mpl_stub'
alias mplscripts='cd ~/gdr/projects/mpl_scripts'
alias mplapi='cd ~/gdr/projects/mpl_api'
alias mplreact='cd ~/gdr/projects/mpl_react'
alias mplsim='cd ~/gdr/projects/mpl_sim'
alias mplnode='cd ~/gdr/projects/mpl_import_node'
alias nencrypt='cd ~/gdr/projects/node-encrypt'
alias sub='cd ~/gdr/projects/subscriber_portal'
alias dl='cd ~/gdr/projects/consumer_portal'
alias doc='cd ~/gdr/projects/doc_control_client'
alias dots='cd ~/dotfiles'
alias cook='cd ~/gdr/projects/cookbook-opsworks' 
alias filei='cd ~/gdr/projects/fileimport'
alias sd='cd ~/gdr/projects/sys_doc'
alias fabric='cd ~/gdr/fabric-composer/loan-network'
alias composerui='node /Users/danherman/scratch/composer/packages/composer-website/node_modules/composer-ui/cli.js'

# Easy editing of aliases file
alias ea='vim ~/.bash/bash_aliases'
alias sa='source ~/.bash/bash_aliases;echo "Aliases updated"'

# Easy editing of bash_profile
alias eb='vim ~/.bash_profile'
alias sb='source ~/.bash_profile; echo "Bash profile sourced"'

# Easy editing of tmux.conf file
alias et='vim ~/.tmux.conf'

# Git shortcuts
alias gc='git commit'
alias gcu='git reset HEAD~' # git commit undo
alias gcn='RUBO=no git commit'
alias gpull='git pull'
alias gpush='git push'
alias gpushn='git push --no-verify'
alias gco='git checkout'
alias gs='git status'
alias ga='git add .'
alias gd='git diff'
alias gcd='git log -p -1'
alias gm='git merge'
alias gpushstaging='gco staging;gm master;gpushn;gco master'
alias gpushprod='gco production;gm staging;gpushn;gco master'
alias gpushall='gco staging;gm master;gpushn;gco production;gm staging;gpushn;gco master'

# Serverless shortcuts
alias slsdf='serverless deploy function --function'
alias slsdft='serverless deploy -t function --function'
alias slsd='serverless deploy --stage dev'
alias slspd='serverless deploy --stage prod'
alias slspdf='serverless deploy --stage prod function --function '
alias slsil='serverless invoke local --function'
alias slsdebug='export SLS_DEBUG=*'
alias slsnodebug='unset SLS_DEBUG'
alias slsremove='serverless remove --region us-east-1'
alias slsremovep='serverless remove --stage prod --region us-east-1'

# Docker shortcuts
alias d='docker'
alias di='docker images'
alias dc='docker ps -a'
alias dfile='vi Dockerfile'
alias dbuild='docker build'
alias drm='docker rm'
alias drun='docker run --rm -it '
alias dstopall='docker kill $(docker ps -q)'

# Kubernetes shortcuts
alias k8='kubectl'
alias k8mini='kubectl config use-context minikube'
alias k8switch='kubectl config use-context'
alias k8s='kubectl config get-contexts'

# Node shortcuts
alias lint='npm run lint'
alias nconsole='npm run console'
alias build='npm run build'

# Rails shortcuts
alias rake='be rake'
alias rails='be rails'
alias rspec='be rspec'
alias console='be console'
alias lastmigration='vim `last_rails_migration`'
alias rdbm='be rake db:migrate;RAILS_ENV=test be rake db:migrate'
alias rbenv-update='cd ~/.rbenv;gpull;cd plugins/ruby-build;gpull'

# Dot files management
# Check(no changes) to dotfiles if see if there are any changes
alias dotc='for file in $(diff -qr ~/dotfiles ~/ | grep differ | cut -d " " -f 4); do echo "$file"; done'
# Update dotfiles from system to git repo if there are any changes
alias dotu='for file in $(diff -qr ~/dotfiles ~/ | grep differ | cut -d " " -f 4); do fp "$file"; echo "$file"; done'
# Checke(no changes) to Send updated dotfiles to system
alias dotpc='for file in $(diff -qr ~/ ~/dotfiles | grep differ | cut -d " " -f 4); do echo "$file"; done'
# Update dotfiles from git repo to system
alias dotp='for file in $(diff -qr ~/ ~/dotfiles | grep differ | cut -d " " -f 4); do fpp "$file"; echo "$file"; done'

# SSH/SFTP/SCP tabout from SSH config
complete -o default -o nospace -W "$(grep "^Host" $HOME/.ssh/config | grep -v "[?*]" | cut -d" " -f2)" scp sftp ssh

# Remote tailf command, specify servername to ssh to, and path starting from /var/log to/log/file
# example: remote_tail test-server1 squid/access.log
function remote_tail {
  ssh -t $1 "sudo tailf \"/var/log/$2\""
}

function remote_tail_mpl {
  ssh -t $1 "sudo tailf \"/srv/www/mpl/shared/log/production.log\""
}

function patch_svr {
  ssh -t $1 "sudo yum update -y --skip-broken"
}

function svr_uptime {
  ssh -t $1 "uptime"
}

function fix_clam {
  ssh -t $1 "sudo chown clamav:clamav /var/lib/clamav -R && sudo freshclam"
}

function last_rails_migration {
  find ./db/migrate -type f | xargs ls -tr | tail -n 1
}

function fp {
  cp "$1" ~/dotfiles/"${1#*/*/*/}"
}

function fpp {
  cp -r "$1" ~/"${1#*/*/*/*/}"
}

function top30history {
  history|awk '{print $2}'|sort|uniq -c|sort -rn|head -30|awk '!max{max=$1;}{r="";i=s=100*$1/max;while(i-->0)r=r"#";printf "%50s %5d %s %s",$2,$1,r,"\n";}'
}

function match_csv_col1 {
  awk -F',' 'NR==FNR{c[$1]++;next};c[$1] > 0' $1 $2
}
